name: zapete
version: '0.2.1'
summary: Remote control for any computer in your local network
description: |
  Zapete is a remote control application that allows you to control your computer
  from any device on your local network using a web interface. It supports
  keyboard input, custom command buttons, and touchpad mouse control.

grade: stable
confinement: strict

parts:
  zapete:
    plugin: nodejs
    nodejs-version: "18.17.0"
    source: .
    build-packages:
      - build-essential
    stage-packages:
      - xdotool
    override-build: |
      npm install --production
      snapcraftctl build

apps:
  zapete:
    command: bin/zapete-launch
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - desktop
      - x11
      - wayland
      - opengl
      - home

  zapete-cli:
    command: bin/zapete-cli
    plugs:
      - network
      - home

plugs:
  desktop:
    mount-host-font-cache: false
  x11:
  wayland:
  opengl:

hooks:
  configure:
    plugs: [network]

layout:
  /opt/zapete:
    bind: $SNAP/opt/zapete